[package]
name = "human_ik"
publish = false
edition = { workspace = true }

[dependencies]
bevy = { workspace = true }
bevy_animation_graph = { path = "../../crates/bevy_animation_graph" }
bevy-inspector-egui = { version = "0.28" }
